language: minimal
os: linux
dist: xenial
group: edge
sudo: required

env:
  global:
    # for updates check developer.android.com/studio#downloads (current 26.1.1)
    - ANDROID_SDK_TOOLS=sdk-tools-linux-4333796.zip

before_install:
  # set JAVA_HOME path
  - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
  # download and unzip Android SDK command line tools
  - wget -nv https://dl.google.com/android/repository/$ANDROID_SDK_TOOLS
  - unzip -q $ANDROID_SDK_TOOLS -d $HOME/sdk
  # set SDK tools path variable and ANDROID_HOME
  - export PATH=$PATH:$HOME/sdk/tools/bin
  - export ANDROID_HOME=$HOME/sdk
  # create empty cfg file to prevent sdkmanager warning message
  - mkdir -p $HOME/.android && touch $HOME/.android/repositories.cfg
install:
  # accept licenses for all available packages that have not already been accepted
  - yes | sdkmanager "platforms;android-28"
  - yes | sdkmanager --licenses >/dev/null
  - yes | sdkmanager "platforms;android-28"
before_script:
  - java -version
  - sudo apt-get install openjdk-8-jdk
  - java -version
  # set executable flag for gradle wrapper
  - chmod +x gradlew

script:
  - ./gradlew opensrp-app:clean opensrp-app:jacocoTestReport  --stacktrace
